import type { CartItem } from '../types';
import type { SimulateCheckoutOutput } from '../skills/types';

export type AgentIntent =
  | 'apply_best_coupon_and_simulate_checkout'
  | 'simulate_checkout_without_coupon'
  | 'explain_best_coupon'
  | 'compare_coupons';

export type SkillName =
  | 'get_cart'
  | 'validate_coupon'
  | 'apply_coupon'
  | 'simulate_checkout';

export type StepStatus = 'success' | 'skipped' | 'failed';

export interface AgentRequest {
  userRequest: string;
  cartItems: CartItem[];
  availableCoupons: string[];
}

export interface PlanStep {
  skill: SkillName;
  description: string;
}

export interface ExecutionPlan {
  intent: AgentIntent;
  steps: PlanStep[];
}

export interface StepTrace {
  skill: SkillName;
  input: unknown;
  output: unknown;
  status: StepStatus;
}

export interface ExecutionTrace {
  steps: StepTrace[];
}

// ---------------------------------------------------------------------------
// Planner model interface
// ---------------------------------------------------------------------------

/** Structured output a PlannerModel must return. */
export interface PlannerModelOutput {
  intent: AgentIntent;
}

/**
 * Contract for any planner model implementation.
 * Can be rule-based, fake-LLM, or a real LLM — the planner doesn't care.
 */
export interface PlannerModel {
  resolve(userRequest: string): Promise<PlannerModelOutput>;
}

// ---------------------------------------------------------------------------
// Compare response shape (public contract for compare_coupons intent)
// ---------------------------------------------------------------------------

export interface CompareEntry {
  couponCode: string;
  isValid: boolean;
  discount?: number;
  finalPrice?: number;
}

export interface CompareResult {
  bestCouponCode: string | null;
  comparisons: CompareEntry[];
}

export interface AgentResponse {
  intent: AgentIntent;
  chosenCoupon: string | null;
  finalResult: SimulateCheckoutOutput | null;
  /** Deterministic explanation derived from execution results, not generated by the LLM. */
  explanation: string | null;
  trace: ExecutionTrace;
  /** Populated only for compare_coupons intent. */
  compare?: CompareResult;
}
